execution:
- executor: gatling
  scenario: sample
  concurrency: 10
  ramp-up: 30s
  hold-for: 2m

scenarios:
  sample:
    script: com/rsk/gatling/test/GoogleTestSimulation.scala
    simulation: com.rsk.gatling.test.GoogleTestSimulation
    
modules:
  gatling:
    properties:
      gatling.data.file.bufferSize: 512 # output buffer size, 256 bytes by default
      gatling.charting.noReports: "true"              # disable html reporting