execution:
- executor: gatling
  scenario: demo
  concurrency: 10
  ramp-up: 30s
  hold-for: 2m

scenarios:
  demo:
    default-address: google.com
    headers:
      X-Tracking: false
      Accept: "*/*"
    requests:
    - url: /
      headers:
        Accept: text/html
      assert:
      - contains:
        - " .+sometext.+"
        subject: body
        regexp: true
        not: true
    - url: /reserve.php
      method: POST
      body: 'Some Body Data'
      think-time: 2s
      assert:
      - contains:
        - 200
        subject: http-code
        not: true